/* tslint:disable */
/* eslint-disable */
/**
 * PC E-commerce API
 * Backend API for PC E-commerce Website - Nhom02 Website Ban PC
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nhom02@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemDTO } from './order-item-dto';

export interface OrderDTO {
    'id'?: number;
    'userId'?: number;
    'orderCode'?: string;
    'discountAmount'?: number;
    'finalAmount'?: number;
    'paymentMethod'?: string;
    'paymentStatus'?: string;
    'status'?: string;
    'shippingAddress'?: string;
    'note'?: string;
    'createdAt'?: string;
    'items'?: Array<OrderItemDTO>;
}

