/* tslint:disable */
/* eslint-disable */
/**
 * PC E-commerce API
 * Backend API for PC E-commerce Website - Nhom02 Website Ban PC
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nhom02@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PromotionDetailDTO } from './promotion-detail-dto';

export interface PromotionDTO {
    'id'?: number;
    'name': string;
    'code': string;
    'discountType': string;
    'discountValue': number;
    'startDate': string;
    'endDate': string;
    'isActive': boolean;
    'details'?: Array<PromotionDetailDTO>;
}

